### ISSUE TITLE
erro install

### ISSUE THREAD

**Issue by viniaero** [geeekpi/dockerpi#2]
Aug 29 20:29:15 raspberrypi systemd[1]: Starting GeeekPi Power On/Off Board...
Aug 29 20:29:15 raspberrypi powerboard_daemon[1209]: /usr/sbin/powerboard_daemon: error while loading shared libraries: libwiringPi.so: cannot open shared object file: No such file or directory
Aug 29 20:29:16 raspberrypi systemd[1]: powerboard_daemon.service: Main process exited, code=exited, status=127/n/a
Aug 29 20:29:16 raspberrypi systemd[1]: Failed to start GeeekPi Power On/Off Board.
Aug 29 20:29:16 raspberrypi systemd[1]: powerboard_daemon.service: Unit entered failed state.
Aug 29 20:29:16 raspberrypi systemd[1]: powerboard_daemon.service: Failed with result 'exit-code'.

**Comment by corvus-ch** [comment]
This can not work any longer. Wiring PI is no longer maintained and thus is not available on the Raspberry Pi anymore. See http://wiringpi.com/wiringpi-deprecated/.

**Comment by shauwki** [comment]
Got the same error. I enabled I2C in raspi-config and installed wiringPi by cloning the original repo and make install it according to repo instructions. Then install the geekpi script provided by their page. Reboot and it worked. On my pi3 and 4. It does not always work and sometimes I needed to redo everything. But once installed it did what I needed. After shutdown it shuts the whole setup down which is nice.

**Comment by corvus-ch** [comment]
@shauwki Where did you found the source code of wiringPi? The repository mentioned on http://wiringpi.com/download-and-install/ section "Plan B" is no longer available.

> git.drogon.net is currently unavailable.
> 
> Please look for alternatives for wiringPi, etc.
>
> (I really mean look for an alternative - as in use another GPIO library. also read the news on http://wiringpi.com/news )
>
> -Gordon

**Comment by shauwki** [comment]
https://github.com/WiringPi/WiringPi

This one worked for me. Just clone it on your pi and run: ./install (i don't remember if sudo is required, don't think so)

**Comment by SirFlour** [comment]
thanks a lot that helped to install it on my raspi 4 running aarch64. I just needed in addition to your steps, to follow this steps for 64bit -> see here https://github.com/geeekpi/dockerpi/tree/master/powerboard

only things was strange, i had to create the file /usr/bin/powerboard_daemon64 and then it worked :) maybe there is something missing in the code or something else :)

**Comment by yoyojacky** [comment]
We are  going to update the script and binary files.
