### ISSUE TITLE
Using powerboard with ubuntu 20.04

### ISSUE THREAD

**Issue by Patrick-81** [geeekpi/dockerpi#4]
Hello I have bought this board to power my RPi 4.

The RPi will be enclosed in an aluminum box so the power switch will be inaccessible. Is there any solution to power it just plugin the 12V on the board bypassing the switch ?

Thanks for your answer

**Comment by alanlucas-viotel** [comment]
Hi

I have a similar problem, did you manage to bypass the power switch in the end?

thanks

**Comment by yoyojacky** [comment]
you can try to use the IR remote to control the power swith, it supports IR remote controller turn on and off the power board...
