### ISSUE TITLE
error install on libreelec

### ISSUE THREAD

**Issue by og13270** [geeekpi/dockerpi#5]
The system fil is quite different than raspbian, so i got this error when i try to install :

LibreELEC-salle:~ # wget -qO- https://git.io/fj3b9 | bash
grep: /boot/config.txt: No such file or directory
grep: /boot/config.txt: No such file or directory
sed: /etc/modules: No such file or directory
grep: /etc/modules: No such file or directory
sh: can't create /etc/modules: Read-only file system
Connecting to github.com (140.82.121.3:443)
Connecting to raw.githubusercontent.com (151.101.120.133:443)
wget: can't open '/etc/systemd/system/powerboard_daemon.service': No such file o                              r directory
Connecting to github.com (140.82.121.4:443)
Connecting to raw.githubusercontent.com (151.101.120.133:443)
wget: can't open '/usr/sbin/powerboard_daemon': Read-only file system
chmod: /etc/systemd/system/powerboard_daemon.service: No such file or directory
chmod: /usr/sbin/powerboard_daemon: No such file or directory
chown: /etc/systemd/system/powerboard_daemon.service: No such file or directory
chown: /usr/sbin/powerboard_daemon: No such file or directory
Failed to enable unit: Unit file powerboard_daemon.service does not exist.
LibreELEC-salle:~ # Failed to start powerboard_daemon.service: Unit powerboard_daemon.service not found.

**Comment by yoyojacky** [comment]
sorry ,it does not support LibreELEC/
