### ISSUE TITLE
I want 64bit version powerboard driver.

### ISSUE THREAD

**Issue by jctk** [geeekpi/dockerpi#6]
My raspberry pi is running on 64bit aarch64 OS . So drivers for Powerboard is not work.
There are only 32bit armhf drivers in GitHub /geekpi/dockerpi.
Where are 64bit drivers ?

**Comment by kritch83** [comment]
This would be nice to support...

**Comment by SirFlour** [comment]
yes that would be very great, otherwise it can not really be used on raspi 4 with 64bit :-(

**Comment by SirFlour** [comment]
it worked only partly for me for my raspi 4 64bit :) 

here is how i did it: howto: https://github.com/geeekpi/dockerpi/tree/master/powerboard

install lwiringPi

sudo git clone https://github.com/WiringPi/WiringPi

cd WiringPI

sudo ./build 

sudo restart now

sudo raspi-config

 --> enable I2C

sudo restart now

sudo git clone https://github.com/geeekpi/dockerpi

sudo apt update
sudo apt upgrade -y
sudo apt -y install build-essential gcc g++ cmake
cd dockerpi/powerboard/
sudo gcc powerboard_daemon.c -lwiringPi -O3 -O /usr/bin/powerboard_daemon64

--> here i am getting the error that the file does not exists :( also i am not sure if there needs to be something else in addition to create the file powerboard_daemon64

**Comment by jctk** [comment]
-O is an incorrect option.
`sudo gcc powerboard_daemon.c -lwiringPi -O3 -O /usr/bin/powerboard_daemon64`

-o is a correct option.
`sudo gcc powerboard_daemon.c -lwiringPi -O3 -o /usr/bin/powerboard_daemon64`

**Comment by jctk** [comment]
I can compile it.
But the generated powerboard_deamon64 only shutdown immediately upon startup.
After registering it as a service by referencing the contents of install.sh to try it out, my raspi became a brick that shutdown forever during the boot sequence.
So I deleted powerboard_deamon64 in the SD card on another device and recovered it.

**Comment by SirFlour** [comment]
@jctk  thanks for sharing. i removed the file name and got the a.out and had the same expierences like you. the raspi also doesnot start :_(. i tried to contact @yoyojacky  over the comment notes as he updated the 64bit readme file, but not reply yet. maybe @nickfox-taterli  can help here to provide a compiles file and installing script for 64bits?

**Comment by yoyojacky** [comment]
> My raspberry pi is running on 64bit aarch64 OS . So drivers for Powerboard is not work. There are only 32bit armhf drivers in GitHub /geekpi/dockerpi. Where are 64bit drivers ?

I am working on it , it will be coming soon.

**Comment by yoyojacky** [comment]
> My raspberry pi is running on 64bit aarch64 OS . So drivers for Powerboard is not work. There are only 32bit armhf drivers in GitHub /geekpi/dockerpi. Where are 64bit drivers ?

and what type of your Raspberry Pi ?  raspberry Pi 4B or raspberry Pi 5?

**Comment by jctk** [comment]
The hardware is Raspberry PI 4B.
The operating system is Debian-based StellarMate.
When I submitted this issue it was Bullseye.
Now it is Bookworm.

**Comment by yoyojacky** [comment]
> hen I submitted this issue it was Bullseye.

yes, it's been a long time due to it's heavy duty on my work and we are trying to fix all the bugs on our products.
we are check everything on github, and our website wiki. sorry for keep you waiting for so long time.

**Comment by yoyojacky** [comment]
Recently, My teamate is working on this project, such as testing the code on Raspberry Pi 5, testing it on both 64bit and 32bit Raspberry Pi OS, and  try to fix the bug caused by the wiringpi library's deprecated issue.  rebuild the 64bit and 32bit binary file and update the readme and instructions and so on.
